#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentionmeter, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, I2C_1,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include <GLOBAL2.h>
task main(){
	while(true){
		motor[rightMotor] = vexRT[Ch2]+vexRT[Ch1];
		motor[leftMotor] = vexRT[Ch2]-vexRT[Ch1];
		motor[armMotor] = vexRT[Ch3]+10*(SensorValue[potentionmeter] < 1700)-10*(SensorValue[potentionmeter] > 2100);
		motor[clawMotor] = (vexRT[Btn5U]-vexRT[Btn5D])*100;
	}
}
//the integrated encoders are not working right, I tried looking at the motors and sensors set up, but coudn't figure out the problem
//I know they aren't working becuse the encodercount doesn't change in the system debugger windows.
//this is a reminder for me, (jackie) or you (Griffffffff...in).
